<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c157c64f-1dcc-409a-a11a-548452248385</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src\Controladora\Controladora.csproj" />
    <ProjectReference Include="src\Entidades\Entidades.csproj" />
    <ProjectReference Include="src\Modelo\Modelo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="src\**\*.cs" />
    <Content Remove="src\**" />
    <EmbeddedResource Remove="src\**" />
    <None Remove="src\**" />
  </ItemGroup>

</Project>