<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Audoglio\FINAL ANALISTA\2da iteracion\CarFix-DIPLOMA\Controladora\Controladora.csproj" />
    <ProjectReference Include="..\..\..\Audoglio\FINAL ANALISTA\2da iteracion\CarFix-DIPLOMA\Entidades\Entidades.csproj" />
    <ProjectReference Include="..\..\..\Audoglio\FINAL ANALISTA\2da iteracion\CarFix-DIPLOMA\Modelo\Modelo.csproj" />
  </ItemGroup>

</Project>
